### PR TITLE
Suggested fixes for XS substitution and tests

### LINKED ISSUE #1: Indirect object syntax does not work when Crypt::Skip32::XS is installed
Indirect object syntax does not work when Crypt::Skip32 defers to Crypt::Skip32::XS

Breaks:
```
my $crypto = new Crypt::Skip32 $key;
```

Works:
```
my $cypto = Crypt::Skip32->new($key);
```

Two comments about this. First is that indirect notation [should be discouraged](http://modernperlbooks.com/mt/2009/08/the-problems-with-indirect-object-notation.html), so the documentation could be updated to reflect that. That being said, it would be nice to have an implementation that does not have a regression when it switches to using the XS module even if one is not using best practices.

See also: https://rt.cpan.org/Public/Bug/Display.html?id=98567

### PR DESCRIPTION
**Pull request by johnlaur**
Here is a proposed solution for #1 which aliases the new() method to the XS  module if it is installed. This allows both direct and indirect calls to the object constructor. Unlike the previous method this only aliases `new` in the `Crypto::Skip32` namespace, but the only potential regression would be for code which does not adhere to the documented interface.

I noticed the current version of `t/05xs.t` was not actually testing that the transparent substitution was working, and I modified it to test that creating a new `Crypto::Skip32` object properly returns a `Crypto::Skip32::XS` object. I then added an explicit test for direct and indirect object syntax.

Fixes #1

### CODE REVIEW

**Comment by ehammond** [comment]
@johnlaur Thanks for submitting this.

The test now produces the following errors with perl v5.26.1:

```Crypt-Skip32$ perl t/05xs.t 
Bareword found where operator expected at t/05xs.t line 24, near "new Crypt::Skip32"
	(Do you need to predeclare new?)
Scalar found where operator expected at t/05xs.t line 24, near "Crypt::Skip32 $key"
	(Do you need to predeclare Crypt::Skip32?)
syntax error at t/05xs.t line 24, near "new Crypt::Skip32 "
Global symbol "$cipher" requires explicit package name (did you forget to declare "my $cipher"?) at t/05xs.t line 25.
Execution of t/05xs.t aborted due to compilation errors.```

**Comment by johnlaur** [comment]
@ehammond That is the expected failure before my patch and the root of the reported bug. Are you sure the test is running against the version of Skip32.pm in the PR? E.g. ‘make test’ should succeed while running ‘perl t/05xs.t’ uses the installed version of the module and would fail if a previous version is installed.

BTW my PR does not update version info and the tests do not specify module version which can catch this. I would be happy to include that also.

**Comment by ehammond** [comment]
Version and changelog would be helpful, thanks.

I'll fix the way I was running the test and try again.

**Comment by johnlaur** [comment]
@ehammond I have done some housekeeping:

 * I pulled the changes from your 0.18 CPAN release into the tree since they were not in the repo.
 * I updated the version to 0.19 and the copyrights to 2019.
 * I made some additions to .gitignore based on the various buld modules in use.
 * Crucially, the XS test now requires version 0.19 so will give a more appropriate failure message if run against an older version.

**Comment by johnlaur** [comment]
@ehammond have you been able to take another look at this PR?

**Comment by ehammond** [comment]
@johnlaur 

Thanks for the reminder and thanks for all the work you put in.

I've pulled, merged, tested, pushed, and uploaded to CPAN.

Let me know if I missed anything.

**Comment by johnlaur** [comment]
@ehammond Much appreciated!

**Pull request merged**
